version: "3"
services:
  bot:
    build: .
    container_name: telegram_bot
    env_file:
      - .env
    depends_on:
      - db
    ports:                   
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      bash -c "alembic upgrade head &&
               python bot/main.py"

  db:
    image: postgres:15
    expose:
      - 5432
    env_file:
      - .env

volumes:
  pgdata:
