services:
  db:
    image: postgres
    container_name: db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - app-network

  bot:
    build: .
    depends_on:
      - db
    container_name: telegram_bot
    ports:
      - 80:80
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network: