services:
  db:
    image: postgres
    container_name: db_automehanic
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - app-network

  bot:
    build: .
    depends_on:
      - db
    container_name: telegram_bot
    restart: always
    volumes:
      - .:/app
    networks:
      - app-network


  admin:
    build:
      context: .
      dockerfile: admin.Dockerfile
    container_name: admin
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - db
      - admin
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_config.conf:/etc/nginx/nginx.conf
      - ./bot/api/static:/var/www/static
    networks:
      - app-network

networks:
  app-network: