"""create table

Revision ID: df96003c688f
Revises: 
Create Date: 2024-10-22 23:07:49.982430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df96003c688f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_number', sa.String(length=100), nullable=False),
    sa.Column('cross_numbers', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('default_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('first_lvl_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('second_lvl_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('third_lvl_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fourth_lvl_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('product_group', sa.String(length=255), nullable=True),
    sa.Column('part_type', sa.String(length=255), nullable=True),
    sa.Column('photo_url_1', sa.String(length=500), nullable=True),
    sa.Column('photo_url_2', sa.String(length=500), nullable=True),
    sa.Column('photo_url_3', sa.String(length=500), nullable=True),
    sa.Column('applicability_brands', sa.Text(), nullable=True),
    sa.Column('applicable_tech', sa.String(length=255), nullable=True),
    sa.Column('weight_kg', sa.String(length=255), nullable=True),
    sa.Column('length_m', sa.String(length=255), nullable=True),
    sa.Column('inner_diameter_mm', sa.String(length=255), nullable=True),
    sa.Column('outer_diameter_mm', sa.String(length=255), nullable=True),
    sa.Column('thread_diameter_mm', sa.String(length=255), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_number')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('organization_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'UNDEFINED', 'CANCELLED', name='role'), nullable=False),
    sa.Column('price_level', sa.Enum('DEFAULT', 'FIRST', 'SECOND', 'THIRD', 'FOURTH', name='price_level'), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
