"""empty message

Revision ID: e21214f7e9e7
Revises: 815d1c66b506
Create Date: 2024-10-18 14:17:19.977405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e21214f7e9e7'
down_revision: Union[str, None] = '815d1c66b506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

role_enum = sa.Enum('ADMIN', 'USER', 'UNDEFINED', 'CANCELLED', name='role')
price_level_enum = sa.Enum('DEFAULT', 'FIRST', 'SECOND', 'THIRD', 'FOURTH', name='price_level')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum.create(op.get_bind(), checkfirst=True)
    price_level_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('products', sa.Column('default_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('products', sa.Column('first_lvl_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('second_lvl_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('third_lvl_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_column('products', 'price')
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'USER', 'UNDEFINED', 'CANCELLED', name='role'), nullable=False))
    op.add_column('users', sa.Column('price_level', sa.Enum('DEFAULT', 'FIRST', 'SECOND', 'THIRD', name='price_level'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'price_level')
    op.drop_column('users', 'role')
    op.add_column('products', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('products', 'third_lvl_price')
    op.drop_column('products', 'second_lvl_price')
    op.drop_column('products', 'first_lvl_price')
    op.drop_column('products', 'default_price')
    # ### end Alembic commands ###
