"""empty message

Revision ID: f609ceeb2053
Revises: e21214f7e9e7
Create Date: 2024-10-18 14:26:17.172704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f609ceeb2053'
down_revision: Union[str, None] = 'e21214f7e9e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('fourth_lvl_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'fourth_lvl_price')
    # ### end Alembic commands ###
